name: tarefas
description: "Um app simples para você salvar suas tarefas e anotações do dia a dia"
publish_to: 'none'

version: 1.2.1+21

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

# App Settings
  app_settings: ^5.1.1

# Disable Battery Optimization
  disable_battery_optimization: ^1.1.1

# Dynamic Colors
  dynamic_color: ^1.7.0

# Email
  flutter_email_sender: ^6.0.2

# Firebase
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  firebase_crashlytics: ^4.0.0
  firebase_performance: ^0.10.0

# Flutter Local Notifications
  flutter_local_notifications: ^17.1.2

# Feedback
  feedback:
      git:
        url: https://github.com/hendrilmendes/feedback.git
        path: feedback
        ref: master

# Google
  google_sign_in: ^6.2.1 

# HTTP
  http: ^1.2.1

# Intl
  intl: ^0.19.0

# Package Info
  package_info_plus: ^8.0.0

# Path Provider
  path_provider: ^2.1.2

# Provider
  provider: ^6.1.1

# Review  
  in_app_review: ^2.0.9

# Shared Preferences
  shared_preferences: ^2.2.2

# Timezone
  timezone: ^0.9.3

# Url Launcher
  url_launcher: ^6.3.0

  flutter_localizations:
    sdk: flutter
    
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/img/

fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
