name: tarefas
description: "Um app simples para você salvar suas tarefas e anotações do dia a dia"
publish_to: 'none'

version: 1.1.5+15

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

# Dynamic Colors
  dynamic_color: ^1.7.0

# Email
  flutter_email_sender: ^6.0.2

# Firebase
  firebase_core: ^2.28.0
  firebase_crashlytics: ^3.5.0
  firebase_performance: ^0.9.4
  cloud_firestore: ^4.16.0
  firebase_auth: ^4.19.0

# Feedback
  feedback:
      git:
        url: https://github.com/hendrilmendes/feedback.git
        path: feedback
        ref: master

# Google
  google_sign_in: ^6.2.1 

# HTTP
  http: ^1.2.1
  
# Package Info
  package_info_plus: ^6.0.0

# Path Provider
  path_provider: ^2.1.2

# Provider
  provider: ^6.1.1

# Review  
  in_app_review: ^2.0.9

# Shared Preferences
  shared_preferences: ^2.2.2

# Url Launcher
  url_launcher: ^6.2.4

  flutter_localizations:
    sdk: flutter
    
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/img/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
