name: tarefas
description: "Um app para você salvar suas tarefas e anotações do dia a dia"
publish_to: 'none'

version: 3.0.0+20250619

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

# App Settings
  app_settings: ^6.1.1

# Connectivity Plus
  connectivity_plus: ^6.1.4

# Cupertino Icons  
  cupertino_icons: ^1.0.8

# Device Plus
  device_info_plus: ^11.5.0

# Disable Battery Optimization
  disable_battery_optimization:
      git:
        url: https://github.com/adeeteya/Disable-Battery-Optimizations.git
        ref: fe575d9

# Dynamic Colors
  dynamic_color: ^1.7.0
  

# Firebase
  cloud_firestore: ^5.6.9
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  firebase_crashlytics: ^4.3.7
  firebase_performance: ^0.10.1+7

# Flutter Local Notifications
  flutter_local_notifications: ^19.3.0

# Google
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0

# HTTP
  http: ^1.4.0

# Intl
  intl: ^0.20.0

# Package Info
  package_info_plus: ^8.3.0

# Path Provider
  path_provider: ^2.1.5

# Provider
  provider: ^6.1.5

# Review  
  in_app_review: ^2.0.10

# Share Plus
  share_plus: ^11.0.0

# Shared Preferences
  shared_preferences: ^2.5.3

# Shorebird
  shorebird_code_push: ^2.0.4

# Timezone
  timezone: ^0.10.1

# Toast
  fluttertoast: ^8.2.11

# Url Launcher
  url_launcher: ^6.3.1

# Wiredash
  wiredash: ^2.5.0

  flutter_localizations:
    sdk: flutter
    
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/img/
    - shorebird.yaml
