name: tarefas
description: "Um app simples para você salvar suas tarefas e anotações do dia a dia"
publish_to: 'none'

version: 1.2.0+20

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

# App Settings
  app_settings: ^5.1.1

# Disable Battery Optimization
  disable_battery_optimization: ^1.1.1

# Dynamic Colors
  dynamic_color: ^1.7.0

# Email
  flutter_email_sender: ^6.0.2

# Firebase
  cloud_firestore: ^4.17.3
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_crashlytics: ^3.5.5
  firebase_performance: ^0.9.4+5

# Flutter Local Notifications
  flutter_local_notifications: ^17.1.2

# Feedback
  feedback:
      git:
        url: https://github.com/hendrilmendes/feedback.git
        path: feedback
        ref: master

# Google
  google_sign_in: ^6.2.1 

# HTTP
  http: ^1.2.1

# Intl
  intl: ^0.18.1

# Package Info
  package_info_plus: ^7.0.0

# Path Provider
  path_provider: ^2.1.2

# Provider
  provider: ^6.1.1

# Review  
  in_app_review: ^2.0.9

# Shared Preferences
  shared_preferences: ^2.2.2

# Timezone
  timezone: ^0.9.3

# Url Launcher
  url_launcher: ^6.2.4

  flutter_localizations:
    sdk: flutter
    
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/img/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
