name: tarefas
description: "Um app de lista de tarefas simples"
publish_to: 'none'

version: 1.1.4+14

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

# Dynamic Colors
  dynamic_color: ^1.6.9

# Firebase
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  firebase_performance: ^0.9.3+8
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0

# Google
  google_sign_in: ^6.2.1 

# HTTP
  http: ^1.2.0

# MDI
  material_design_icons_flutter: 5.0.5955-rc.1
  
# Package Info
  package_info_plus: ^5.0.1

# Provider
  provider: ^6.1.1

# Shared Preferences
  shared_preferences: ^2.2.2

# Url Launcher
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/img/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
