// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTg9QaCdocUlDM1loDK4ESHB_1uqdxwoM',
    appId: '1:68248536741:web:0daab0f0bf1835dddfaf4c',
    messagingSenderId: '68248536741',
    projectId: 'tarefas-app-66907',
    authDomain: 'tarefas-app-66907.firebaseapp.com',
    storageBucket: 'tarefas-app-66907.appspot.com',
    measurementId: 'G-VEEJRXC5RD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSWF-Il2JrCLJwdWL6oSdJVvaOAzupvz8',
    appId: '1:68248536741:android:feab21c748de6d39dfaf4c',
    messagingSenderId: '68248536741',
    projectId: 'tarefas-app-66907',
    storageBucket: 'tarefas-app-66907.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9C2oBMS9YEn9s3do9XVu80JU7pRlLEBs',
    appId: '1:68248536741:ios:f279c58b0e740f7edfaf4c',
    messagingSenderId: '68248536741',
    projectId: 'tarefas-app-66907',
    storageBucket: 'tarefas-app-66907.appspot.com',
    iosBundleId: 'com.github.hendrilmendes.tarefas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9C2oBMS9YEn9s3do9XVu80JU7pRlLEBs',
    appId: '1:68248536741:ios:0bc31e1a160373abdfaf4c',
    messagingSenderId: '68248536741',
    projectId: 'tarefas-app-66907',
    storageBucket: 'tarefas-app-66907.appspot.com',
    iosBundleId: 'com.github.hendrilmendes.tarefas.RunnerTests',
  );
}
